name: Deploy Staging to Heroku

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "maib-backend-staging"
          heroku_email: "gteam.officials@gmail.com"
        run: npm run strapi admin:reset-user-password --email="gteam.officials@gmail.com" --password="Gteamofficial1"
